notifications:
  email: false

language: cpp
dist: focal

branches:
  only:
  - main

compiler:
  - gcc
  - clang

os:
  - linux

arch:
  - amd64

before_script:
  - mkdir build
  - cd build && cmake ..

script:
  - cd $TRAVIS_BUILD_DIR/build
  - make
  - ctest --verbose